language: rust
rust:
  - 1.10.0
  - beta
  - nightly
sudo: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libusb-1.0-0-dev
install:
  - git clone https://github.com/jpoirier/librtlsdr.git
  - cd librtlsdr && mkdir build && cd build && cmake ../ && make && sudo make install && sudo ldconfig && cd ~
script:
  - cargo build --verbose
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = nightly ] &&
  echo '<meta http-equiv=refresh content=0;url=/rust-rtlsdr/rtlsdr/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure:
notifications:
  email:
on_success: never
